# Generated by Django 5.2.9 on 2025-12-27 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='researchreasoning',
            options={},
        ),
        migrations.RenameField(
            model_name='researchcost',
            old_name='recorded_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='researchreasoning',
            old_name='content',
            new_name='reason',
        ),
        migrations.RemoveField(
            model_name='researchcost',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='researchcost',
            name='description',
        ),
        migrations.RemoveField(
            model_name='researchreasoning',
            name='step_number',
        ),
        migrations.RemoveField(
            model_name='researchsession',
            name='user',
        ),
        migrations.AddField(
            model_name='researchcost',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchsession',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='researchsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='researchcost',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research_app.researchsession'),
        ),
        migrations.AlterField(
            model_name='researchreasoning',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research_app.researchsession'),
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research_app.researchsession'),
        ),
    ]
