# Generated by Django 5.2.9 on 2025-12-27 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_app', '0002_alter_researchreasoning_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchcost',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='researchcost',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='research_app.researchsession'),
        ),
        migrations.AlterField(
            model_name='researchreasoning',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasonings', to='research_app.researchsession'),
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='research_app.researchsession'),
        ),
    ]
