# Generated by Django 5.2.9 on 2025-12-28 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_app', '0003_alter_researchcost_amount_alter_researchcost_session_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchreasoning',
            old_name='reason',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='researchsession',
            name='description',
        ),
        migrations.RemoveField(
            model_name='researchsession',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='UploadedDocument',
        ),
    ]
