# Generated by Django 5.2.9 on 2025-12-28 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_app', '0004_rename_reason_researchreasoning_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchcost',
            old_name='amount',
            new_name='cost',
        ),
        migrations.AddField(
            model_name='researchsession',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchcost',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research_app.researchsession'),
        ),
        migrations.AlterField(
            model_name='researchreasoning',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research_app.researchsession'),
        ),
        migrations.AlterField(
            model_name='researchsession',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
