# Generated by Django 5.2.9 on 2025-12-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_app', '0005_rename_amount_researchcost_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchreasoning',
            old_name='content',
            new_name='reasoning',
        ),
        migrations.RemoveField(
            model_name='researchcost',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='researchreasoning',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='researchsession',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='researchcost',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
