# Generated by Django 5.2.9 on 2025-12-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_app', '0006_rename_content_researchreasoning_reasoning_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchcost',
            name='cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='researchsession',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='researchsession',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
